# Generated by Django 5.1.6 on 2025-03-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritegolfer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favoritegolfer',
            name='rank',
        ),
    ]
