# Generated by Django 5.1.6 on 2025-03-05 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_favoritegolfer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritegolfer',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4'), (5, 'Tier 5')], default=1),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4'), (5, 'Tier 5')]),
        ),
        migrations.AlterUniqueTogether(
            name='favoritegolfer',
            unique_together={('user', 'tier')},
        ),
    ]
